name: ci

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * 0"]

jobs:

  test-release-build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Toolchain
        run: |
          rustup toolchain install "$(cat rust-toolchain)"
          rustup show

      - name: Build | Release Mode
        run: cargo build --release

  unittest:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Toolchain
        run: |
          rustup toolchain install "$(cat rust-toolchain)"
          rustup show

      - name: Test
        run: cargo test
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: full

  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Toolchain
        run: |
          rustup toolchain install "$(cat rust-toolchain)" \
            --component rustfmt --component clippy
          rustup show

      - name: Format
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --no-deps --workspace --all-targets -- -D warnings

      - name: Build-doc
        run: cargo doc --all --no-deps
        env:
          RUSTDOCFLAGS: "-D warnings"
